<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dtgjzymdi/image/upload/v1554381245/p_ass.jpg" alt="Adepoju Odunayo">
                        <h6>Adepoju Odunayo</h6>
                        <p>Android Developer, Data Science Enthusiast</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/AdepojuOdun" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ogadepoju" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://ogadepoju.blogspot.com/" target="_blank"<i class="fab fa-blogspot fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm an android developer who is vast with android studio and also a data science and machine learning Enthusiast.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | Python | C# | Graphics design</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
